TITLE	MOUSE(EXE) PROGRAMMING
PAGE 60,132

;DISPLAY STRING MACRO---------------------------------------
DISPLAYS MACRO STRING
	MOV AH,09H
	MOV DX,OFFSET STRING
	INT 21H
	ENDM
;-----------------------------------------------------------

;CURSOR MACRO ROW,COL---------------------------------------
CURSOR MACRO ROW,COL
	MOV AH,02H
	MOV BH,00H
	MOV DH,ROW
	MOV DL,COL
	INT 10H
	ENDM
;-----------------------------------------------------------

;FILL MACRO ROWS,COLS,ROWE,COLE,COLOR-----------------------
FILL MACRO ROWS,COLS,ROWE,COLE,COLOR
	LOCAL START,AGAIN
	MOV DX,ROWS
START:	MOV CX,COLS
AGAIN:	MOV AH,0CH
	MOV AL,COLOR
	INT 10H
	INC CX
	CMP CX,COLE
	JNE AGAIN
	INC DX
	CMP DX,ROWE
	JNE START
	ENDM
;-----------------------------------------------------------
.MODEL SMALL
.STACK 64
.DATA
	MESSAGE1	DB	'THIS IS USING INT 33H FOR MOUSE','$'
	MESSAGE2	DB	'IT WORKS! ','$'
	MESSAGE3	DB	'CLICK IN THE BOX TO SEE WHAT HAPPENS!','$'
	MESSAGE4	DB	'ANG SABI KO! IN THE BOX!','$'	
	MESSAGE5	DB	'NOW PRESS ANY KEY PARA MAKA EXIT','$'
	OLDVID		DB	?
	NEWVID		DB	12H

.CODE
MAIN PROC FAR
	MOV AX,@DATA
	MOV DS,AX

	MOV AH,0FH	;CURRENT VIDEO MODE
	INT 10H

	MOV OLDVID,AL	;SAVE IT

	MOV AX,0600H	;CLEAR SCREEN
	MOV BH,07H
	MOV CX,0000H
	MOV DX,184FH
	INT 10H

	MOV AH,00H	;SET NEW VIDEO MODE
	MOV AL,NEWVID
	INT 10H

	CURSOR 0,0
	FILL 150,250,250,350,4	;DRAW RED BOX
	
	CURSOR 1,1
	DISPLAYS MESSAGE1

	CURSOR 5,22
	DISPLAYS MESSAGE3

	

	MOV AX,0000H	;INITIALIZE MOUSE
	INT 33H

	MOV AX,01H	;SHOW MOUSE CURSOR
	INT 33H

AGAIN:	MOV AX,03H	;GET MOUSE LOCATION
	INT 33H

	CMP BX,0001H	;CHECK IF LEFT BUTTON IS PRESSED
	JNE AGAIN

	CMP CX,250
	JB NOTINSIDE

	CMP CX,350
	JA NOTINSIDE

	CMP DX,150
	JB NOTINSIDE

	CMP DX,250
	JA NOTINSIDE

	CURSOR 18,18
	DISPLAYS MESSAGE2
	JMP EXIT

NOTINSIDE:	CURSOR 20,18
		DISPLAYS MESSAGE4

EXIT:	MOV AH,02H
	INT 33H
	CURSOR 22,18
	MOV AH,07H
	INT 21H
	MOV AH,0
	MOV AL,OLDVID
	INT 10H

	MOV AH,4CH
	INT 21H
MAIN ENDP
	END MAIN
